export const UPDATE_LOGIN_FORM_DATA = 'UPDATE_LOGIN_FORM_DATA';
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_LOGIN_FAILED_TRUE = 'SET_LOGIN_FAILED_TRUE';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';

export const FETCH_DETAILS_FOR_SINGLE_PRODUCT = 'FETCH_DETAILS_FOR_SINGLE_PRODUCT';
export const ADD_SELECTED_PRODUCT_TO_CART = 'ADD_SELECTED_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const GET_SEARCH_INPUT = 'GET_SEARCH_INPUT';
export const DISPLAY_SEARCH_RESULTS = 'DISPLAY_SEARCH_RESULTS';
export const CLEAR_THE_SEARCHBAR_INPUT = 'CLEAR_THE_SEARCHBAR_INPUT';
export const EMPTY_SEARCH_RESULT_ARRAY = 'EMPTY_SEARCH_RESULT_ARRAY';