export const UPDATE_LOGIN_FORM_DATA = 'UPDATE_LOGIN_FORM_DATA';
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_LOGIN_FAILED_TRUE = 'SET_LOGIN_FAILED_TRUE';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';

export const FETCH_DETAILS_FOR_SINGLE_PRODUCT = 'FETCH_DETAILS_FOR_SINGLE_PRODUCT';